# Generated by Django 4.1.7 on 2023-03-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.books'),
            preserve_default=False,
        ),
    ]
