# Generated by Django 4.1.7 on 2023-03-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_books_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(choices=[(1, 'Fiction'), (2, 'Novel'), (3, 'Biography'), (4, 'Story'), (5, 'History')], max_length=100),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='book_covers/'),
        ),
    ]
