# Generated by Django 4.1.7 on 2023-03-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_category_cat_name_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Novel', 'Novel'), ('Biography', 'Biography'), ('Story', 'Story'), ('History', 'History')], max_length=100),
        ),
    ]
