# Generated by Django 4.1.7 on 2023-03-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_category_cat_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='images',
            new_name='Image',
        ),
    ]
