# Generated by Django 4.1.7 on 2023-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_category_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(choices=[('fiction', 'fiction'), ('novel', 'fovel'), ('biography', 'fiography'), ('story', 'ftory'), ('history', 'fistory')], max_length=100),
        ),
    ]
