# Generated by Django 4.1.7 on 2023-04-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='dashboard.book'),
        ),
    ]
