# Generated by Django 4.1.7 on 2023-04-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_variation_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
