# Generated by Django 4.1.7 on 2023-04-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_book_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_text', models.CharField(max_length=150, null=True)),
                ('discount_percentage', models.IntegerField(null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
