# Generated by Django 4.1.7 on 2023-04-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_text',
            field=models.CharField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
