# Generated by Django 4.1.7 on 2023-04-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_coupon_coupon_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.IntegerField(blank=True),
        ),
    ]
