# Generated by Django 4.1.7 on 2023-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_book_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_category',
            name='book',
        ),
        migrations.RemoveField(
            model_name='book_category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='book_category',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
