# Generated by Django 4.1.7 on 2023-04-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_book_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
