# Generated by Django 4.1.7 on 2023-04-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('pdf', 'PDF'), ('paperback', 'Paperback'), ('audio', 'Audio')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='dashboard.book')),
            ],
        ),
    ]
