# Generated by Django 4.1.7 on 2023-04-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_bookvariation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookVariation',
        ),
    ]
