# Generated by Django 4.1.7 on 2023-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_bookvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvariation',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
