# Generated by Django 4.1.7 on 2023-04-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_bookvariation_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookvariation',
            name='stock',
        ),
    ]
