# Generated by Django 4.1.7 on 2023-04-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_bookvariation_book_alter_bookvariation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvariation',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_variation', to='dashboard.book'),
        ),
    ]
