# Generated by Django 4.1.7 on 2023-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvariation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bookvariation',
            name='variation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
