# Generated by Django 4.1.7 on 2023-05-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
