# Generated by Django 4.1.7 on 2023-03-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=9747237363, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
