# Generated by Django 4.1.7 on 2023-04-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_bookvariation_price_and_more'),
        ('cart', '0004_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='dashboard.bookvariation'),
        ),
    ]
