# Generated by Django 4.1.7 on 2023-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_address1_address_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(max_length=255),
        ),
    ]
