# Generated by Django 4.1.7 on 2023-04-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_provider_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razorpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=150)),
            ],
        ),
    ]
