# Generated by Django 4.1.7 on 2023-04-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_razorpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay',
            name='payment_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='razorpay',
            name='signature_id',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
    ]
