# Generated by Django 4.1.7 on 2023-04-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_razorpay_payment_id_razorpay_signature_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
