# Generated by Django 4.1.7 on 2023-04-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_razorpay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpay',
            name='payment_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='razorpay',
            name='signature_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
