# Generated by Django 4.1.7 on 2023-04-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amound_paid',
            field=models.CharField(max_length=50),
        ),
    ]
