# Generated by Django 4.1.7 on 2023-04-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_payment_amound_paid_payment_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='book_edition',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
    ]
